name: Create PR to env/qa after Sprint merge
on:
  pull_request:
    branches: 
      - sprints/sprint1
    types: 
      - closed
jobs:
  sync-branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Create Sync PR
        uses: sudoStatus200/create-sync-pr@0.3.1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SOURCE_BRANCH: "sprints/sprint1"
          TARGET_BRANCH: "env/qa"
