

name: MergeToSprint

on:
  pull_request:
    branches: 
      - sprints/sprint1
    types: [closed]

jobs:
  merge-sprint-to-qa:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Merge sprint1 to env/qa
      run: |  
          echo The PR was merged to sprints/sprint1!          
          git fetch --unshallow
          git checkout env/qa
          git pull origin sprints/sprint1
          git merge --no-ff origin/sprints/sprint1 -m "Auto-merge sprint1 to env/qa"
          git push
          echo Success!

        
