
name: MergeToMain

on:
  pull_request:
    branches: 
      - revert-4-test-5
    types: 
      -closed

jobs:
  my-action:
    if: ${{ github.event.pull_request.merged }}

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: Success!

