name: OnSprintLabedMergeToQA

on:
  pull_request:
    branches: 
      - env/qa
    types: 
      - closed

jobs:
  if_merged_and_labeled:
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'sprint1')
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cherry pick into sprints/sprint1
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: sprints/sprint1
          labels: |
            autocreated
            sprint1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
