name: OnSprintLabedMergeToQA

on:
  pull_request:
    branches: 
      - env/qa
    types: 
      - closed

jobs:
  if_merged_and_labeled:
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'sprint1')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # The token of the user that should perform the merges. 
          # This must be a personal access token with the necessary permissions
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Autodev
        uses: Staffbase/autodev-action@v1.5.1
        with:
          # The token used to fetch the pull requests from the GitHub API
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          branch:	'sprints/sprint1'
          label:	'sprint1'
