name: OnSprintLabedMergeToQA

on:
  pull_request:
    branches: 
      - env/qa
    types: 
      - closed

jobs:
  if_merged_and_labeled:
    if: |
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'sprint')
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug log
        run: echo S! 
