name: SprintPRAutoMerge

on:
  pull_request:
    branches: 
      - sprints/sprint1
    types: [labeled, opened]
    
  workflow_dispatch:

jobs:
  automerge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'autocreated')
      && contains(github.event.pull_request.labels.*.name, 'sprint1')
    runs-on: ubuntu-latest
    steps:
      - name: Info log
        run: echo OK!
