name: SprintPRAutoMerge

on:
  pull_request:
    branches: 
      - sprints/sprint1
    types: [labeled, opened]
    
  workflow_dispatch:

jobs:
  automerge:
    if: |
      contains(github.event.pull_request.labels.*.name, 'autocreated')
      && contains(github.event.pull_request.labels.*.name, 'sprint1')
    runs-on: ubuntu-latest
    steps:
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 1
        method: squash
        repo: juliangruber/octokit-action
