name: QA-Merge

on:
  pull_request:
    branches: 
      - env/qa
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: env/qa merge
      run: |  
          echo ENV/QA was merged
          echo Success!
