name: MergeToSprint1

on:
  push:
    branches: 
      - env/qa
    types: [closed]

jobs:
  if_merged:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'sprint/sprint1'
          target: 'env/qa'
