name: TEST

on:
  pull_request:
    branches: 
      - main
    types:
      - labeled
      - submitted

jobs:
  build:
    if: ${{ github.event.label.name == 'test_label' }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo TEST GITHUB ACTION RUN!

