name: TEST

on:
  pull_request:
    branches: 
      - main
    types: [ labeled ]
  pull_request_review:
    types:
      - submitted

jobs:
  build:
    if: ${{ github.event.label.name == 'test_label' }}
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo TEST GITHUB ACTION RUN!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
