name: MergeToSprint1

on:
  push:
    branches: 
      - sprint/sprint1

jobs:
  update-qa-branch:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'sprint/sprint1'
          target: 'env/qa'
