name: MergeToSprint1

on:
  pull_request:
    branches: 
      - sprints/sprint1
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'sprints/sprint1'
          target: 'env/qa'
